spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: oracle.jdbc.driver.OracleDriver
##    url: jdbc:oracle:thin:@127.0.0.1:1521:test
##    username: test
##    password: test
#
#
#    url: jdbc:oracle:thin:@10.5.245.8:1521:billdb
#    username: db_exe
#    password: db_exe123
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    names: spring


server:
  port: 8082

mybatis:
  type-aliases-package: com.spring.demo.code.*.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
